apiVersion: apps/v1
kind: Deployment
metadata:
  name: mt-backend
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: mt-backend
  template:
    metadata:
      labels:
        app: mt-backend
    spec:
      containers:
        - name: mt-backend
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - containerPort: {{ .Values.service.port }}
          env:
            - name: POSTGRES_HOST
              value: mt-postgresql.mt-database.svc.cluster.local
            - name: POSTGRES_USER
              valueFrom:
                secretKeyRef:
                  name: mt-postgresql
                  key: postgres-user
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mt-postgresql
                  key: postgres-password

