apiVersion: apps/v1
kind: Deployment
metadata:
  name: mt-backend
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: mt-backend
  template:
    metadata:
      labels:
        app: mt-backend
    spec:
      containers:
        - name: mt-backend
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - containerPort: 5000
          env:
          - name: DB_HOST
            value: {{ .Values.db.host | quote }}
          - name: DB_USER
            value: {{ .Values.db.user | quote }}
          - name: DB_PASSWORD
            value: {{ .Values.db.password | quote }}
          - name: DB_NAME
            value: {{ .Values.db.name | quote }}

