apiVersion: v1
kind: Service
metadata:
  name: mt-backend
spec:
  selector:
    app: mt-backend
  ports:
    - protocol: TCP
      port: {{ .Values.service.port }}
      targetPort: 5000
      {{- if eq .Values.service.type "NodePort" }}
      nodePort: {{ .Values.service.nodePort }}
      {{- end }}
  type: {{ .Values.service.type }}
