apiVersion: v2
name: postgresql
description: Wrapper for Bitnami PostgreSQL Helm chart
type: application
version: 0.1.0
appVersion: "1.16.0"
dependencies:
  - name: postgresql
    version: 12.11.1
    repository: https://charts.bitnami.com/bitnami
