apiVersion: v1
kind: Service
metadata:
  name: mt-frontend
spec:
  type: {{ .Values.service.type }}
  selector:
    app: mt-frontend
  ports:
    - port: {{ .Values.service.port }}
      targetPort: 80
      nodePort: {{ .Values.service.nodePort }}
