replicaCount: 1

image:
  repository: mt-frontend
  tag: latest
  pullPolicy: IfNotPresent

service:
  type: NodePort
  port: 80
  nodePort: 30085

content:
  index.html: |
    <html>
      <body>
        <h1>Hello from Michael's Frontend!</h1>
        <p>Calling backend at /api</p>
      </body>
    </html>

backend:
  url: http://192.168.49.2:30086
